openapi: 3.0.1
info:
  description: Kintone REST API
  version: 1.0.0
  title: Kintone REST API
servers:
  - url: 'http://127.0.0.1:8080/unsecure'
paths:
  /getCookies:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /testPrecedenceHeader:
    get:
      parameters:
        - in: header
          name: API-KEY
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /testPrecedenceQuery:
    get:
      parameters:
        - in: query
          name: API-KEY
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /testPrecedenceCookie:
    get:
      parameters:
        - in: cookie
          name: API-KEY
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /getAutoCookie:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /getRequestHeaders:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /getQueryParameters:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /getHeader:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    apiTokenAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    appId:
      type: apiKey
      in: header
      name: X-APP-ID
security:
  - apiTokenAuth: []
  - appId: []
